### PR TITLE
add macos build

### PR DESCRIPTION
**Pull request by matthiasdiener**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
osx 64 in 2024? do you want to add the arm build too?

**Comment by hmaarrfk** [comment]
why don't you follow the standard to test only on native and emulated?

**Comment by matthiasdiener** [comment]
> why don't you follow the standard to test only on native and emulated?

If I did that, wouldn't that also skip the `test -f $PREFIX/bin/nvtop` test?

**Comment by hmaarrfk** [comment]
> If I did that, wouldn't that also skip the test -f $PREFIX/bin/nvtop test?

yes. but it follow more of our standard practices so when we do get osx arm runners the tests will run

**Comment by matthiasdiener** [comment]
> > If I did that, wouldn't that also skip the test -f $PREFIX/bin/nvtop test?
> 
> yes. but it follow more of our standard practices so when we do get osx arm runners the tests will run

Sounds good. This is ready for another look.

**Pull request merged**
